- name: Install packeges
  become: true
  apt:
    pkg:
      - gnupg
      - curl
    state: latest
    update_cache: yes

- name: Add mongo repo key
  shell: |
    curl -fsSL https://pgp.mongodb.com/server-7.0.asc | \
    sudo gpg -o /usr/share/keyrings/mongodb-server-7.0.gpg \
    --dearmor --yes

- name: Add apt source
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse"
    state: present
    filename: mongodb

- name: Install mongo
  become: true
  apt:
    pkg:
      - mongodb-org
    state: latest
    update_cache: yes

- name: Start and enable the MongoDB
  become: true
  systemd:
    name: mongod
    state: started
    enabled: true

# По умолчанию MongoDB слушает 127.0.0.1:27017, есть доступ без пароля
# Для включения обязательного пароля:
# echo -e "security\nauthorization: enabled\n" >> /etc/mongod.conf
